
CREATE VIEW serviceRequestsVW AS

select 
    "Unique Key",
    CAST("Created Date" as date)  as 'Created Date',
    "Closed Date",
    Agency,
    "Agency Name",
    "Complaint Type",
    Descriptor,
    COALESCE("Location Type",'UnSpscified') as "Location Type",
    "Incident Zip",
    COALESCE("Incident Address",'Unspecified') as "Incident Address",
    COALESCE("Street Name",'Unspecified') as "Street Name",
    COALESCE("Cross Street 1",'Unspecified') as "Cross Street 1",
    COALESCE("Cross Street 2",'Unspecified') as "Cross Street 2",
    COALESCE("Intersection Street 1",'Unspecified') as "Intersection Street 1",
    COALESCE("Intersection Street 2",'Unspecified') as "Intersection Street 2",
    COALESCE("Address Type",'Unspecified') as "Address Type",
    COALESCE("City",'Unspecified') as "City",
    COALESCE("Landmark",'Unspecified') as "Landmark",
    COALESCE("Facility Type",'Unspecified') as "Facility Type",
    COALESCE("Status",'Unspecified') as "Status",
    CAST("Due Date" as date)  as 'Due Date',
    "Resolution Description",
    CAST("Resolution Action Updated Date" as date)  as 'Resolution Action Updated Date',
    COALESCE("Community Board",'Unspecified') as "Community Board",
    BBL,
    COALESCE("Borough",'Unspecified') as "Borough",
    "X Coordinate (State Plane)",
    "Y Coordinate (State Plane)",
    COALESCE("Open Data Channel Type",'Unspecified') as "Open Data Channel Type",
    "Park Facility Name",
    COALESCE("Vehicle Type",'Unspecified') as "Park Borough",
    COALESCE("Taxi Company Borough",'Unspecified') as "Taxi Company Borough",
    COALESCE("Taxi Pick Up Location",'Unspecified') as "Taxi Pick Up Location",
    COALESCE("Bridge Highway Name",'Unspecified') as "Bridge Highway Name",
    COALESCE("Bridge Highway Direction",'Unspecified') as "Bridge Highway Direction",
    COALESCE("Bridge Highway Segment",'Unspecified') as "Bridge Highway Segment",
    COALESCE("Road Ramp",'Unspecified') as "Road Ramp",
    Longitude,
    Latitude,
    "Location"
from serviceRequests
